// Generated by OpenClaw / Codeavour on 2026-05-10 for Project Pulse build order. Source: Project_Pulse_Strategy.docx v1.
import { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';

const DemoExplorer: NextPage = () => {
  const [query, setQuery] = useState('');
  const [response, setResponse] = useState('');

  const handleQueryChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setQuery(e.target.value);
  };

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const response = await fetch('/api/iris', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ query })
    });
    const result = await response.json();
    setResponse(result.data);
  };

  return (
    <div>
      <Head>
        <title>DataCo - Demo Explorer</title>
      </Head>
      <div className="split-pane">
        <div className="input-pane">
          <label htmlFor="query" style={{ color: 'red' }}>SYNTHETIC DEMO DATA — NOT REAL PATIENTS</label>
          <form onSubmit={handleSubmit}>
            <textarea id="query" placeholder="e.g., How many CHF patients on amiodarone with invasive monitoring between 2022–2025?" onChange={handleQueryChange}></textarea>
            <button type="submit">Ask Iris</button>
          </form>
        </div>
        <div className="results-pane">
          <pre>{response}</pre>
          <p>⚠️ SYNTHETIC DEMO DATA — NOT REAL PATIENTS. Results are illustrative only. Contact us for a feasibility study against our real federated dataset.</p>
        </div>
      </div>
      <footer>
        <p>Demo environment. Production platform forthcoming. No real patient data on this site.</p>
      </footer>
    </div>
  );
};

export default DemoExplorer;
