// Generated by OpenClaw / Codeavour on 2026-05-10 for Project Pulse build order. Source: Project_Pulse_Strategy.docx v1.
"use client";
import { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';

const Demo: NextPage = () => {
  const [email, setEmail] = useState('');

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setEmail(e.target.value);
  };

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const response = await fetch('/api/demo-access', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email })
    });
    const result = await response.json();
    if (result.ok) {
      window.location.href = '/demo/explorer';
    }
  };

  return (
    <div>
      <Head>
        <title>DataCo - Demo Access</title>
      </Head>
      <form onSubmit={handleSubmit}>
        <input name="email" type="email" placeholder="Enter your email" onChange={handleChange} />
        <button type="submit">Request Access</button>
      </form>
      <footer>
        <p>Demo environment. Production platform forthcoming. No real patient data on this site.</p>
      </footer>
    </div>
  );
};

export default Demo;
