// Generated by OpenClaw / Codeavour on 2026-05-10 for Project Pulse build order. Source: Project_Pulse_Strategy.docx v1.
import { NextApiRequest, NextApiResponse } from 'next';

const contactHandler = async (req: NextApiRequest, res: NextApiResponse) => {
  if (req.method === 'POST') {
    const { name, company, role, email, description, therapeuticArea, context } = req.body;
    const message = `🔔 New lead: ${name} / ${company} / ${role} / ${email}\nNeed: ${description}${therapeuticArea ? `\nTherapeutic area: ${therapeuticArea}` : ''}${context ? `\nSource: ${context}` : ''}`;

    try {
      const telegramRes = await fetch(`https://api.telegram.org/bot8270911338:AAFHtw_Ukn8TK2u5H0ncY1c106bEd-7O1vU/sendMessage`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ chat_id: '-1003816869841', message_thread_id: 3585, text: message })
      });

      if (telegramRes.ok) {
        res.status(200).json({ success: true });
      } else {
        res.status(500).json({ success: false, message: 'Failed to send message to Telegram' });
      }
    } catch (error) {
      res.status(500).json({ success: false, message: 'Error occurred while sending message to Telegram' });
    }
  } else {
    res.setHeader('Allow', ['POST']);
    res.status(405).end(`Method ${req.method} Not Allowed`);
  }
};

export default contactHandler;
