// Generated by OpenClaw / Codeavour on 2026-05-10 for Project Pulse build order. Source: Project_Pulse_Strategy.docx v1.
import { NextApiRequest, NextApiResponse } from 'next';
import fs from 'fs';
import path from 'path';

const demoAccessHandler = async (req: NextApiRequest, res: NextApiResponse) => {
  if (req.method === 'POST') {
    const { email } = req.body;
    const filePath = path.join('/tmp', 'demo-emails.txt');

    try {
      fs.appendFileSync(filePath, `${email}\n`);
      res.status(200).json({ ok: true });
    } catch (error) {
      res.status(500).json({ ok: false, message: 'Error occurred while storing email' });
    }
  } else {
    res.setHeader('Allow', ['POST']);
    res.status(405).end(`Method ${req.method} Not Allowed`);
  }
};

export default demoAccessHandler;
