// Generated by OpenClaw / Codeavour on 2026-05-10 for Project Pulse build order. Source: Project_Pulse_Strategy.docx v1.
import { NextPage } from 'next';
import Head from 'next/head';

const About: NextPage = () => {
  return (
    <div>
      <Head>
        <title>DataCo - About</title>
      </Head>
      <section>
        <h2>What We Are</h2>
        <p>DataCo is designed as an AI-first operating company. Three humans. Eleven agents.</p>
      </section>
      <section>
        <h2>Agent Roster</h2>
        <ul>
          <li>Iris: AI agent</li>
          <li>Sentinel: AI agent</li>
          <li>Mira: AI agent</li>
          <li>Rafa: AI agent</li>
          <li>Lin: AI agent</li>
          <li>Kepler: AI agent</li>
          <li>Notary: AI agent</li>
          <li>Atlas: AI agent</li>
          <li>Ledger: AI agent</li>
          <li>Hermes: AI agent</li>
          <li>Forge: AI agent</li>
        </ul>
      </section>
      <section>
        <h2>Why AI-Native?</h2>
        <p>Cost structure, speed, 24/7 availability — but human accountability at every legal/regulatory gate</p>
        <p>Placeholders: [FOUNDER], [HEAD_OF_TRUST_AND_GOVERNANCE], [SCIENTIFIC_ADVISORY_BOARD_MEMBER_1]</p>
      </section>
      <footer>
        <p>Demo environment. Production platform forthcoming. No real patient data on this site.</p>
      </footer>
    </div>
  );
};

export default About;
