// Generated by OpenClaw / Codeavour on 2026-05-10 for Project Pulse build order. Source: Project_Pulse_Strategy.docx v1.
import { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';

const Contact: NextPage = () => {
  const [formData, setFormData] = useState({ name: '', company: '', role: '', email: '', description: '' });

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    setFormData({ ...formData, [name]: value });
  };

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const response = await fetch('/api/contact', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(formData)
    });
    const result = await response.json();
    console.log(result);
  };

  return (
    <div>
      <Head>
        <title>DataCo - Contact</title>
      </Head>
      <form onSubmit={handleSubmit}>
        <input name="name" placeholder="Name" onChange={handleChange} />
        <input name="company" placeholder="Company" onChange={handleChange} />
        <input name="role" placeholder="Role" onChange={handleChange} />
        <input name="email" type="email" placeholder="Email" onChange={handleChange} />
        <textarea name="description" placeholder="Describe your data need" onChange={handleChange}></textarea>
        <button type="submit">Submit</button>
      </form>
      <footer>
        <p>Demo environment. Production platform forthcoming. No real patient data on this site.</p>
      </footer>
    </div>
  );
};

export default Contact;
