// Generated by OpenClaw / Codeavour on 2026-05-10 for Project Pulse build order. Source: Project_Pulse_Strategy.docx v1.
import { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>DataCo - Real-World Evidence</title>
      </Head>
      <header>
        <h1>Longitudinal ICU and device data. Federated. Query-ready.</h1>
      </header>
      <section>
        <h2>Problem</h2>
        <p>Pharma RWE feasibility takes 6-9 weeks; DataCo delivers in days. Source: McKesson Compile's own pitch language on "prolonged back-and-forth cycles".</p>
      </section>
      <section>
        <h2>Wedge</h2>
        <p>What EHR-only vendors (TriNetX, Flatiron, Aetion) structurally cannot match — continuous waveform, device, and PDMS data from complex acute care units. Non-US comparator dataset (Türkiye, GCC).</p>
      </section>
      <section>
        <h2>Federated model</h2>
        <div className="federated-model">
          <p>eConnect source → De-id gateway → Discovery warehouse. Note: "No underlying data movement. Your analysis runs inside our infrastructure."</p>
        </div>
      </section>
      <section>
        <h2>Pricing</h2>
        <ul>
          <li>Bronze (feasibility queries, indicative $40-80K/yr)</li>
          <li>Silver (+ TRE access, $150-250K/yr)</li>
          <li>Gold (+ AI Explorer, custom partners, $400K+/yr)</li>
        </ul>
        <p>Request access</p>
      </section>
      <footer>
        <p>Demo environment. Production platform forthcoming. No real patient data on this site.</p>
        <a href="/contact">Request access to the synthetic demo →</a>
      </footer>
    </div>
  );
};

export default Home;
