// Generated by OpenClaw / Codeavour on 2026-05-10 for Project Pulse build order. Source: Project_Pulse_Strategy.docx v1.
import { NextPage } from 'next';
import Head from 'next/head';

const HowItWorks: NextPage = () => {
  return (
    <div>
      <Head>
        <title>DataCo - How It Works</title>
      </Head>
      <section>
        <h2>Pipeline A (Discovery)</h2>
        <p>eConnect → De-id gateway → OMOP warehouse → Cohort builder</p>
      </section>
      <section>
        <h2>Pipeline B (Analysis)</h2>
        <p>Scoped cohort → TRE provisioning → Notebook environment → Sentinel airlock → Approved output</p>
      </section>
      <section className="callout">
        <h3>Key Principle</h3>
        <p>No raw records leave the source perimeter. Every artefact passes disclosure control before release.</p>
      </section>
      <section>
        <h2>Audit Trail</h2>
        <p>Every query, every export, retained 10 years</p>
      </section>
      <footer>
        <p>Demo environment. Production platform forthcoming. No real patient data on this site.</p>
      </footer>
    </div>
  );
};

export default HowItWorks;
